// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxDKgzDPp0icYET_bIUB--7X77xU1ruI',
    appId: '1:688972749821:web:00f1e90759a95c4deb9794',
    messagingSenderId: '688972749821',
    projectId: 'stock-vente-pos',
    authDomain: 'stock-vente-pos.firebaseapp.com',
    storageBucket: 'stock-vente-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0DqSBp_dMVGELeMRfKNLtA3daN9a5Y0',
    appId: '1:688972749821:android:f3f1a664598c6c1deb9794',
    messagingSenderId: '688972749821',
    projectId: 'stock-vente-pos',
    storageBucket: 'stock-vente-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHOxLSBvs8uyhEKcGvCGh3lH1-7-vbCno',
    appId: '1:688972749821:ios:80c310028f673c95eb9794',
    messagingSenderId: '688972749821',
    projectId: 'stock-vente-pos',
    storageBucket: 'stock-vente-pos.firebasestorage.app',
    iosBundleId: 'com.example.stockVentePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHOxLSBvs8uyhEKcGvCGh3lH1-7-vbCno',
    appId: '1:688972749821:ios:80c310028f673c95eb9794',
    messagingSenderId: '688972749821',
    projectId: 'stock-vente-pos',
    storageBucket: 'stock-vente-pos.firebasestorage.app',
    iosBundleId: 'com.example.stockVentePos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxDKgzDPp0icYET_bIUB--7X77xU1ruI',
    appId: '1:688972749821:web:37abe1dc5da3860aeb9794',
    messagingSenderId: '688972749821',
    projectId: 'stock-vente-pos',
    authDomain: 'stock-vente-pos.firebaseapp.com',
    storageBucket: 'stock-vente-pos.firebasestorage.app',
  );
}
